### PR TITLE
Update to linting

### PR DESCRIPTION
**Pull request by Tathanen**
A simple minor release candidate, just matching the standards in dominatr.

### CODE REVIEW

**Comment by Tathanen** [comment]
Patch!  Not minor.

**Comment by Tathanen** [comment]
@jrit / @dmaloneycalu

**Comment by jrit** [comment]
I don't even think you need a release for this, it is just an internal thing, it has no influence on any installed use. LGTM other than that.

**Comment by dmaloneycalu** [comment]
Agree with Jarrett. These files won't be installed unless directly working on d-g anyways

**Comment by Tathanen** [comment]
Okey dokey, version big removed.

**Pull request merged**
