### PR TITLE
Update grunt-contrib-jshint

### PR DESCRIPTION
**Pull request by Tathanen**
@jrit @dmaloneycalu 

As noted in https://github.com/vokal/dominatr/pull/114, need updated version to support latest jshint changes in dominatr

### CODE REVIEW

**Comment by dmaloneycalu** [comment]
LGTM

**Comment by Tathanen** [comment]
`6.1.3` pls

**Comment by dmaloneycalu** [comment]
https://github.com/vokal/dominatr-grunt/releases/tag/v6.1.3

**Comment by Tathanen** [comment]
:+1:

**Pull request merged**
